name: liquidctl 
base: core22
summary: a status and control utility to for power, cooling and LED components
description: |
     liquidctl is a command-line tool to monitor and control the fan speed,
     LED colour and pump volumes of specific power supplies, motherboards, 
     graphics cards and cooling solutions.
     The liquidctl snap unofficial and is not endorsed by the upsteam project.
adopt-info: liquidctl
grade: stable
confinement: strict

architectures:
  - build-on: [amd64]

apps:
  liquidctl:
    command: bin/liquidctl
    plugs:
      - raw-usb
      - uhid
      - hardware-observe

parts:
  liquidctl:
    plugin: python
    source-type: git
    source: https://github.com/liquidctl/liquidctl
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version \
      "$(git describe --long --tags --always --match=v*.*.* | sed 's/v//')"
    stage-packages:
       - python3-setuptools
       - python3-docopt
       - python3-colorlog
       - python3-smbus
       - python3-usb
    override-build: |
      snapcraftctl build
      python -m pip install .
      sed -i '1c#!\/usr\/bin\/env python3' "$SNAPCRAFT_PART_INSTALL/bin/liquidctl"
#      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin/"
#      cp "$SNAPCRAFT_PART_BUILD/install/bin/liquidctl" "$SNAPCRAFT_PART_INSTALL/bin/liquidctl"
